import { generateKeyPairSync, sign } from "node:crypto";
import { splitSigned, parsePayload, verifySignature } from "./adReward.ts";
const { privateKey, publicKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
const msg = "ad_network=5450213213286189855&ad_unit=1234567890&custom_data=a%2Fb&key_id=3335741209&reward_amount=5&reward_item=uses&timestamp=1507770365237823&transaction_id=18fa792de1bca816048293fc71035638&user_id=uid123";
const sig = sign("sha256", Buffer.from(msg), { key: privateKey, dsaEncoding: "der" }).toString("base64").replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const q = `${msg}&signature=${sig}&key_id=3335741209`;
let fails = 0; const t=(n:string,c:boolean)=>{console.log(c?"PASS":"FAIL",n); if(!c)fails++;};
const s = splitSigned(q)!;
t("message cut raw keeps %2F", s.message === msg);
t("valid signature verifies", verifySignature(s.message, s.signature, publicKey));
const p = parsePayload(q)!;
t("payload parsed", p.userId==="uid123" && p.rewardAmount===5 && p.customData==="a/b");
const tampered = q.replace("reward_amount=5","reward_amount=500");
const s2 = splitSigned(tampered)!;
t("tampered amount rejected", !verifySignature(s2.message, s2.signature, publicKey));
const reencoded = new URLSearchParams(msg).toString();
t("re-encoded query would fail (why we cut raw)", !verifySignature(reencoded.replace("%2F","/"), s.signature, publicKey) || reencoded===msg);
t("missing signature -> null", splitSigned(msg)===null);
process.exit(fails);
